language: common-lisp
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - LD_LIBRARY_PATH=$HOME/hdf5/lib/
    - CPATH=$HOME/hdf5/include/
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl
    - LISP=cmucl
    - LISP=alisp

matrix:
  allow_failures:
    - env: LISP=clisp
    - env: LISP=abcl
    - env: LISP=ecl
    - env: LISP=cmucl
    - env: LISP=alisp

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - pwd
  - test -f "$HOME/hdf5/lib/libhdf5.a" || ( curl -L https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.10.1.tar.gz | tar xz ; cd hdf5-1.10.1; ./configure --prefix=$HOME/hdf5 ; make install )

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp
    - $HOME/hdf5

script:
  - echo "hi!"
  - ./test.ros
