
(in-package #:hdf5)

(defparameter *test-failures* nil)

(defun testhdf5 ()
    (load-hdf5-foreign-libraries)
    (do-external-symbols (s (find-package "HDF5"))
      (print s))

    ;; basics
    (load "examples/basics/h5-cmprss")
    (load "examples/basics/h5-crtdat")
    (load "examples/basics/h5-crtatt")
    (load "examples/basics/h5-crtgrp")
    (load "examples/basics/h5-crtgrpar")
    (load "examples/basics/h5-crtgrpd")
    (load "examples/basics/h5-extend")
    (load "examples/basics/h5-rdwt")
    (load "examples/basics/h5-subset")

    ;; datasets
    (load "examples/datasets/h5ex-d-alloc")
    (load "examples/datasets/h5ex-d-checksum")
    (load "examples/datasets/h5ex-d-chunk")
    (load "examples/datasets/h5ex-d-compact")
    (load "examples/datasets/h5ex-d-extern")
    (load "examples/datasets/h5ex-d-fillval")
    (load "examples/datasets/h5ex-d-gzip")
    (load "examples/datasets/h5ex-d-hyper")
    (load "examples/datasets/h5ex-d-nbit")
    (load "examples/datasets/h5ex-d-rdwr")
    (load "examples/datasets/h5ex-d-shuffle")
    (load "examples/datasets/h5ex-d-sofloat")
    (load "examples/datasets/h5ex-d-soint")
    (load "examples/datasets/h5ex-d-szip")
    (load "examples/datasets/h5ex-d-transform")
    (load "examples/datasets/h5ex-d-unlimadd")
    (load "examples/datasets/h5ex-d-unlimgzip")
    (load "examples/datasets/h5ex-d-unlimmod")

    ;; datatypes
    (load "examples/datatypes/h5ex-t-array")
    (load "examples/datatypes/h5ex-t-arrayatt")
    (load "examples/datatypes/h5ex-t-bit")
    (load "examples/datatypes/h5ex-t-bitatt")
    (load "examples/datatypes/h5ex-t-cmpd")
    (load "examples/datatypes/h5ex-t-cmpdatt")
    (load "examples/datatypes/h5ex-t-commit")
    (load "examples/datatypes/h5ex-t-convert")
    (load "examples/datatypes/h5ex-t-cpxcmpd")
    (load "examples/datatypes/h5ex-t-cpxcmpdatt")
    (load "examples/datatypes/h5ex-t-enum")
    (load "examples/datatypes/h5ex-t-enumatt")
    (load "examples/datatypes/h5ex-t-float")
    (load "examples/datatypes/h5ex-t-floatatt")
    (load "examples/datatypes/h5ex-t-int")
    (load "examples/datatypes/h5ex-t-intatt")
    (load "examples/datatypes/h5ex-t-objref")
    (load "examples/datatypes/h5ex-t-objrefatt")
    (load "examples/datatypes/h5ex-t-opaque")
    (load "examples/datatypes/h5ex-t-opaqueatt")
    (load "examples/datatypes/h5ex-t-regref")
    (load "examples/datatypes/h5ex-t-regrefatt")
    (load "examples/datatypes/h5ex-t-string")
    (load "examples/datatypes/h5ex-t-stringatt")
    (load "examples/datatypes/h5ex-t-vlen")
    (load "examples/datatypes/h5ex-t-vlenatt")
    (load "examples/datatypes/h5ex-t-vlstring")
    (load "examples/datatypes/h5ex-t-vlstringatt")

    ;; groups
    (load "examples/groups/h5ex-g-compact")
    (load "examples/groups/h5ex-g-corder")
    (load "examples/groups/h5ex-g-create")
    (load "examples/groups/h5ex-g-intermediate")
    (load "examples/groups/h5ex-g-iterate")
    (load "examples/groups/h5ex-g-phase")
    (load "examples/groups/h5ex-g-traverse")
    (load "examples/groups/h5ex-g-visit"))

(eval-when (:load-toplevel :execute)
  (testhdf5)
  #+sbcl(sb-ext:exit))
